version: "3.8"

services:
  express:
    build: ./express
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    working_dir: /usr/src/app/server
    command: ["node", "server.js"]
    depends_on:
      - mongo
      - redis
      - mosquitto

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  python:
    image: python:3.10
    container_name: python
    volumes:
      - ./python:/usr/src/app
    working_dir: /usr/src/app

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "start"]
    ports:
      - "8080:8080"

volumes:
  mongo-data:
