services:
  express:
    build: ./express
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    working_dir: /usr/src/app/
    command: ["node", "server.js"]
    depends_on:
      - mongo
      - redis
      - mosquitto

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo-data:/data/db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis/config/redis.conf:/usr/local/etc/redis/config/redis.conf
  #     - redis-data:/data
  #   command: ["redis-server", "/usr/local/etc/redis/config/redis.conf"]
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis/config/redis.conf:/usr/local/etc/redis/config/redis.conf
  #     - ./redis/redis-data:/data
  #     - ./redis/log:/var/log/redis
  #     - ./redis/data:/var/lib/redis # Add this line to map the directory
  #   command: ["redis-server", "/usr/local/etc/redis/config/redis.conf"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/data

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # python:
  #   image: python:3.10
  #   container_name: python
  #   volumes:
  #     - ./python:/usr/src/app
  #   working_dir: /usr/src/app

  # frontend:
  #   image: node:18
  #   container_name: frontend
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   command: ["npm", "start"]
  #   ports:
  #     - "8080:8080"

volumes:
  mongo-data:
  redis-data:
